
# set the BASENAME for the config files. This will also 
# be used for the .lib, .lef, .v, and .spef files
# that are generated by this script
setMultiCpuUsage -localCpu max
# set BASENAME "snn_fixed_16_2_4_4_2"

# set the name of the filler cells - you don't need a list
# if you only have one
set fillerCells [list "scs130lp_fill_1" "scs130lp_fill_2" "scs130lp_fill_4" "scs130lp_fill_8"]
setDoAssign on -buffer scs130lp_buf_1

# choose numbers that make sense for you
set usepct 0.4;# percent utilization in placing cells
set rowgap 0 ;# gap between pairs of std cell rows
set aspect 0.7;# aspect ratio of overall cell (1.0 is square)
# less than 1.0 is landscape, greaterF than 1.0 is portrait

#############################################################
# You may not have to change things below this line - but check!
#############################################################
set clockBufName scs130lp_clkbuf_1;# Footprint of inverter in .lib file

# Set some values that define the power rings and stripes. 
# use these defaults, or choose your own. 
# Note that all these numbers should  be divisible by 3 so 
# that they fit on the lambda grid
set pwidth 0.5   ;# power rail width
set pspace 1.0    ;# power rail space
set swidth 1.0    ;# power stripe width
set sspace 1;# power stripe spacing
set soffset 1.0;# power stripe offset to first stripe
set coregap 4.0;# gap between the core and the power rails 
set set_to_set_distance 3.0;

set init_gnd_net vgnd
set init_pwr_net vpwr
set init_lef_file {../../lib/s130.tlef
/afs/glue.umd.edu/department/enee/software/cadskywaterpdk/S130IP/DIG/current/scs130lp/lef/scs130lp.lef}
set init_verilog ../../synthesis/work/output/${BASENAME}_pg_syn.v
set init_mmmc_file ../scripts/Default.view

init_design

# source the files that operate on the circuit
source ../scripts/fplan.tcl  ;# create the floorplan (might be done by hand...)
# saveNetlist [format "%s_soc.v" $BASENAME] -includePowerGround
source ../scripts/pplan.tcl  ;# create the power rings and stripes
# source pin.tcl
# source pin_fix.tcl


addWellTap -cell scs130lp_tapvpwrvgnd_1 -cellInterval 50 -checkerBoard
source ../scripts/place.tcl  ;# Place the cells and optimize (pre-CTS)
addTieHiLo -cell scs130lp_conb_1 -prefix tieOff
#source cts.tcl    ;# Create the clock tree, and optimize (post-CTS)
source ../scripts/route.tcl  ;# Route the design using nanoRoute
source ../scripts/verify.tcl ;# Verify the design and produce output files
# exit
