#!/bin/bash

# a simple bash script for Cadence Genus

echo "Genus Synthesis Control Script"

# Read target_library and target_library_path from ../lib/lib_path
target_library=$(grep '^target_library=' ../lib/lib_path | cut -d'=' -f2)
library_search_path=$(grep '^library_search_path=' ../lib/lib_path | cut -d'=' -f2)

if [ -z "$target_library" ]; then
    echo "Error: target_library not found in ../lib/lib_path."
    exit 1
fi
if [ -z "$library_search_path" ]; then
    echo "Error: library_search_path not found in ../lib/lib_path."
    exit 1
fi

echo "target_library: $target_library"
echo "library_search_path: $library_search_path"

# reset control variables
gui=0
topmodule=""
newtopflag=0
top=0

# read and process input arguments
for arg in $@
do
    if [ "$arg" == "-gui" ]
    then
	gui=1
    elif [ $newtopflag == 1 ]
    then
	topmodule=$arg
	newtopflag=0
    elif [ "$arg" == "-top" ]
    then
	newtopflag=1
        top=1
    fi
done

echo ""
pushd work


if [ $gui == 1 ]
then
   if [ $top == 1 ]
   then
      genus -execute "set target_library $target_library; set_db init_lib_search_path $library_search_path; set top_module $topmodule" -f ../scripts/synthesis.tcl -gui
   else
      genus -gui
   fi
else
   if [ $top == 1 ]
   then
      genus -execute "set target_library $target_library; set_db init_lib_search_path $library_search_path; set top_module $topmodule" -f ../scripts/synthesis.tcl 
   else
      genus
   fi
fi

echo "Deleting following log files"
find . -maxdepth 1 -type f 
find . -maxdepth 1 -type f -exec rm -f {} \;

popd


	
